### ISSUE TITLE
Commands have incorrect arguments when executed from console / command blocks.

### ISSUE THREAD

**Issue by el-piedras** [GeheimagentNr1/DimensionAccessManager#2]
**Versions**
Minecraft: 1.18.2
Forge: 40.2.4
Mod: 3.0.1

**The bug**
Basically, I'm trying to unlock the nether after certain quest with HQM is completed, which runs the following command:
`dimension minecraft:the_nether access grant`
When this command is ran from the chat, as the player, it works as intended, but when ran from the HQM book, or command blocks, it tells me the arguments are incorrect.

**Stuff I tried**
- I tried running variations of the `dimension` command that would serve the same purpose, like whitelisting individual players, or using `execute as @p run [...] @s[type=player]` to fix it, but nothing seemed to work.  

Executed from player:
![image](https://github.com/GeheimagentNr1/DimensionAccessManager/assets/134638269/68796ea3-dc6f-4c6f-87fd-a497e1d56a01)

Executed from command block:
![image](https://github.com/GeheimagentNr1/DimensionAccessManager/assets/134638269/ee598b13-bbcf-4903-b2e8-a15234760146)

Executed from HQM book:
![image](https://github.com/GeheimagentNr1/DimensionAccessManager/assets/134638269/de16d3e9-acda-4907-a2da-e33794889037)

┆Issue is synchronized with this [Trello card](https://trello.com/c/EJeN1OLi) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>3.1.0</td></tr><tr><th>Fix release date:</th><td>13.08.23</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.18.2  
    Forge version: 40.2.4  
    Mod version: 3.0.4
*   Minecraft version: 1.19.4  
    Forge version: 45.0.64  
    Mod version: 3.0.4

**TODOs:**

*   [x] Test with Minecraft: 1.18.2, Forge: 40.2.4, Mod: 3.0.4
*   [x] Test with Minecraft: 1.19.4, Forge: 45.0.64, Mod: 3.0.4
*   [x] Make commands required op level configurable

**Comment by GeheimagentNr1** [comment]
The issue is more about, that currently the grant/lock and whitelist/blacklist commands need op level 4. But command blocks and the HQM book only use op level 2.  
I will try to make the op level, that is required to run the commands configurable.

**Comment by GeheimagentNr1** [comment]
The issue was fixed with version 3.1.0 for Minecraft versions 1.18.2, 1.19.2, 1.19.4, 1.20.1.  
  
There is now a new configuration value: dimension\_command\_permission\_level  
It defines, which permission level is required to run the /dimension command  
Default = 3  
Available values = 0, 1, 2, 3, 4  
By default, only operators, that can change the whitelist, can change the dimension permissions.  
If the commands shall be executed by a command block of i.e. HQM the permission level has to be 2 or less.  
More details about minecraft permission levels, you can find here: [https://minecraft.fandom.com/wiki/Permission_level](https://minecraft.fandom.com/wiki/Permission_level)
